"""Package the selected real TCN and Python preprocessing references for Flutter."""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

from word_data import load_recording
from word_dataset import SequenceStandardizer, prepare_examples

ROOT = Path(__file__).resolve().parents[1]


def main() -> None:
    run = ROOT / "backend/models/word_runs/demo-real-v1"
    selection = json.loads((run / "selection.json").read_text())
    if selection["selected_architecture"] != "tcn" or selection["data_origin"] != "real":
        raise ValueError("Expected the selected real TCN run")
    metadata = json.loads((run / "tcn/model_metadata.json").read_text())
    source = ROOT / "backend/recorded_data/trials_1.csv"
    if hashlib.sha256(source.read_bytes()).hexdigest() != metadata["source_files"][0]["sha256"]:
        raise ValueError("Source recording changed since training")
    model = (run / "tcn/model.tflite").read_bytes()
    digest = hashlib.sha256(model).hexdigest()
    if digest != "7664ceacd04b488fc896b04210490e4c0908d852050ad22ed4dc2b80fe561a8a":
        raise ValueError("Selected model bytes changed")
    bundle = ROOT / "flutter_app/assets/models/words_tcn"
    bundle.mkdir(parents=True, exist_ok=True)
    (bundle / "model.tflite").write_bytes(model)
    metadata["deployment"] = {
        "tflite_sha256": digest,
        "runtime": "Flutter tflite_flutter 0.12.1 CPU; attempt-owned background isolate",
        "gesture_boundaries": "user starts and finishes one complete attempt",
        "minimum_confidence_percent": 80,
        "hardware_validation": "Not run",
    }
    (bundle / "model_metadata.json").write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")
    recording = load_recording(source, manifest_path=source.with_name("manifest_1.json"))
    examples = prepare_examples([recording], window_samples=96, target_rate_hz=40)
    standardizer = SequenceStandardizer.from_dict(metadata["standardizer"])
    selected_trials = {item["trial"] for item in selection["selected_test_trials"]}
    samples = recording.trials()
    references = []
    for example in examples:
        if example.trial_key not in selected_trials:
            continue
        trial = next(rows for rows in samples.values() if rows[0].trial_id == example.trial_id)
        references.append({
            "trial": example.trial_key, "label": example.word,
            "raw_packets": [row.raw_packet for row in trial],
            "frames": [{"t_ms": row.device_timestamp_ms, "seq": row.device_sequence,
                        "values": row.features} for row in trial],
            "expected_input": standardizer.transform(example.values).tolist(),
        })
    fixture = ROOT / "flutter_app/test/fixtures/word_preprocessing.json"
    fixture.parent.mkdir(parents=True, exist_ok=True)
    fixture.write_text(json.dumps({"scope": "Software preprocessing parity only; already evaluated recorded test trials, not new accuracy evidence", "trials": references}) + "\n", encoding="utf-8")
    replay = [{"label": item["label"], "raw_packets": item["raw_packets"],
               "expected_confidence": next(max(trial["probabilities"]) * 100
                   for trial in selection["selected_test_trials"] if trial["expected"] == item["label"])}
              for item in references]
    replay_path = ROOT / "flutter_app/integration_test/fixtures/word_replay.dart"
    replay_path.parent.mkdir(parents=True, exist_ok=True)
    replay_path.write_text("// Generated by backend/export_word_demo_bundle.py.\n"
        "// Recorded replay checks software integration, not new live accuracy.\n"
        "const wordReplayJson = r'''" + json.dumps(replay) + "''';\n", encoding="utf-8")
    print(f"Packaged {len(model)} bytes, SHA256 {digest}; {len(references)} preprocessing references")


if __name__ == "__main__":
    main()
