"""Train the static flex MLP on real recordings with firmware-matched calibration.

Whole session/trial groups are assigned to splits; frames are never randomly
split across training and evaluation. The synthetic baseline is left intact.
"""
from __future__ import annotations

import argparse
import faulthandler
import hashlib
import json
import re
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score
from sklearn.preprocessing import StandardScaler
import tensorflow as tf

from word_models import convert_to_tflite

ROOT = Path(__file__).resolve().parents[1]
FEATURES = [f"flex_{finger}_raw" for finger in ("thumb", "index", "middle", "ring", "pinky")]


def save_json(path: Path, value: object) -> None:
    path.write_text(json.dumps(value, indent=2, allow_nan=False) + "\n", encoding="utf-8")


def firmware_calibration(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    enabled = re.search(r"kUseFlexModelCalibration\s*=\s*(true|false)", text)
    count = re.search(r"kCalibratedFlexCount\s*=\s*(\d+)", text)
    if enabled is None or count is None:
        raise ValueError("Missing firmware calibration configuration")
    config = {"enabled": enabled[1] == "true", "sensor_count": int(count[1])}
    for name in ("kFlexMeasuredStraight", "kFlexMeasuredBent", "kFlexModelStraight", "kFlexModelBent"):
        match = re.search(name + r"\[[^\]]+\]\s*=\s*\{([^}]+)\}", text)
        if match is None:
            raise ValueError(f"Missing {name}")
        config[name] = [float(value.strip().removesuffix("f")) for value in match[1].split(",")]
        if len(config[name]) != config["sensor_count"]:
            raise ValueError(f"Wrong endpoint count for {name}")
    if not 0 <= config["sensor_count"] <= len(FEATURES):
        raise ValueError("Invalid calibrated sensor count")
    for straight, bent in zip(config["kFlexMeasuredStraight"], config["kFlexMeasuredBent"]):
        if not np.isfinite([straight, bent]).all() or straight <= bent:
            raise ValueError("Invalid measured calibration window")
    return config


def calibrate(values: np.ndarray, config: dict) -> np.ndarray:
    result = np.asarray(values, dtype=np.float32).copy()
    if config["enabled"]:
        for index in range(config["sensor_count"]):
            bent = np.float32(config["kFlexMeasuredBent"][index])
            straight = np.float32(config["kFlexMeasuredStraight"][index])
            target_bent = np.float32(config["kFlexModelBent"][index])
            target_straight = np.float32(config["kFlexModelStraight"][index])
            position = np.clip((result[:, index] - bent) / (straight - bent), 0, 1)
            result[:, index] = target_bent + position * (target_straight - target_bent)
    return result


def write_header(path: Path, model_bytes: bytes, labels: list[str], mean: np.ndarray,
                 scale: np.ndarray, config: dict) -> None:
    def floats(values):
        return ", ".join(f"{float(value):.9e}f" for value in values)

    lines = ["#pragma once", "", "// Generated by backend/train_static_recorded.py; do not edit by hand.",
             f"// TFLite SHA256: {hashlib.sha256(model_bytes).hexdigest()}",
             f"constexpr int kRecordedClassCount = {len(labels)};",
             f"constexpr float kRecordedFeatureMean[5] = {{{floats(mean)}}};",
             f"constexpr float kRecordedFeatureScale[5] = {{{floats(scale)}}};",
             "const char* const kRecordedClassLabels[kRecordedClassCount] = {" +
             ", ".join(json.dumps(label) for label in labels) + "};",
             f"static_assert(kUseFlexModelCalibration == {'true' if config['enabled'] else 'false'},",
             '              "Recorded model calibration changed; retrain the model.");',
             f"static_assert(kCalibratedFlexCount == {config['sensor_count']},",
             '              "Recorded model calibration channel count changed.");']
    for name in ("kFlexMeasuredStraight", "kFlexMeasuredBent", "kFlexModelStraight", "kFlexModelBent"):
        for index, value in enumerate(config[name]):
            lines += [f"static_assert({name}[{index}] == {float(value):.9e}f,",
                      '              "Recorded model calibration endpoints changed; retrain.");']
    lines += ['static_assert(!kUseHardcodedMlTest, "Recorded model requires live sensor input.");',
              "alignas(16) const unsigned char g_asl_model_tflite[] = {"]
    for offset in range(0, len(model_bytes), 12):
        lines.append("  " + ", ".join(f"0x{value:02x}" for value in model_bytes[offset:offset+12]) + ",")
    lines += ["};", f"const unsigned int g_asl_model_tflite_len = {len(model_bytes)};", ""]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("csv", type=Path, nargs="+")
    parser.add_argument("--output-directory", type=Path, required=True)
    parser.add_argument("--export-header", type=Path)
    parser.add_argument("--epochs", type=int, default=80)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--priority-labels", nargs="*", default=[])
    parser.add_argument("--priority-weight", type=float, default=1.0)
    parser.add_argument("--replace-priority-with-latest-source", action="store_true")
    args = parser.parse_args()
    faulthandler.dump_traceback_later(90, repeat=True)
    if args.output_directory.exists():
        raise ValueError("Use a new output directory to preserve previous runs")
    if args.epochs < 1:
        raise ValueError("Epoch count must be positive")
    priority = {label.upper() for label in args.priority_labels}
    if not np.isfinite(args.priority_weight) or args.priority_weight <= 0:
        raise ValueError("Priority weight must be positive and finite")
    tf.config.threading.set_inter_op_parallelism_threads(2)
    tf.config.threading.set_intra_op_parallelism_threads(2)
    tf.keras.utils.set_random_seed(args.seed)
    config = firmware_calibration(ROOT / "ESP32/include/firmware_config.h")
    sources, frames = [], []
    for source_index, path in enumerate(args.csv):
        frame = pd.read_csv(path)
        required = set(FEATURES + ["session_id", "trial_id", "word", "sample_index", "packet_valid", "vocabulary_version"])
        if not required.issubset(frame.columns):
            raise ValueError(f"Missing recording columns in {path}")
        if not frame["vocabulary_version"].eq("static-asl-v1").all():
            raise ValueError("Only static-asl-v1 real recordings may be used")
        frame["label"] = frame.word.astype(str).str.upper()
        if not frame.label.str.fullmatch(r"[A-Z0-9]").all():
            raise ValueError("Invalid static class label")
        if not frame.packet_valid.astype(str).str.lower().eq("true").all():
            raise ValueError("Invalid packets require a separately reviewed exclusion policy")
        values = frame[FEATURES].to_numpy(dtype=np.float32)
        if not np.isfinite(values).all() or (values < 0).any() or (values > 4095).any():
            raise ValueError("Invalid raw ADC readings")
        sources.append({"path": path.as_posix(), "sha256": hashlib.sha256(path.read_bytes()).hexdigest(), "frames": len(frame)})
        frame["source_index"] = source_index
        frames.append(frame)
    data = pd.concat(frames, ignore_index=True)
    if data.duplicated(["session_id", "trial_id", "sample_index"]).any():
        raise ValueError("Duplicate frames or repeated source recordings")
    excluded = []
    if args.replace_priority_with_latest_source:
        keep = np.ones(len(data), dtype=bool)
        for label in sorted(priority):
            selected = data.label.eq(label)
            if not selected.any():
                raise ValueError(f"Priority label {label} has no recordings")
            latest = int(data.loc[selected, "source_index"].max())
            drop = selected & data.source_index.ne(latest)
            excluded.append({"label": label, "frames": int(drop.sum()), "reason": "use latest supplied source for priority label"})
            keep &= ~drop.to_numpy()
        data = data.loc[keep].reset_index(drop=True)
    data["group"] = data.session_id + "/" + data.trial_id
    if (data.groupby("group").label.nunique() != 1).any():
        raise ValueError("A trial contains multiple labels")
    labels = sorted(data.label.unique().tolist())
    if len(labels) < 2:
        raise ValueError("At least two classes are required")
    if priority - set(labels):
        raise ValueError("A priority label is missing from the selected recordings")
    rng = np.random.default_rng(args.seed)
    assignments, counts = {}, {}
    for label in labels:
        groups = sorted(data.loc[data.label.eq(label), "group"].unique())
        rng.shuffle(groups)
        counts[label] = len(groups)
        # Sparse pilot classes remain train-only. No frame-level fallback split.
        for index, group in enumerate(groups):
            split = ("test" if index == 0 else "validation" if index == 1 else "train") if len(groups) >= 3 else "train"
            assignments[group] = split
    data["split"] = data.group.map(assignments)
    x = calibrate(data[FEATURES].to_numpy(), config)
    y = np.array([labels.index(label) for label in data.label], dtype=np.int32)
    masks = {split: data.split.eq(split).to_numpy() for split in ("train", "validation", "test")}
    if not masks["validation"].any() or not masks["test"].any():
        raise ValueError("Independent validation and test trials are required")
    # Each class and each trial within that class receive equal total weight.
    train = data.loc[masks["train"]]
    trial_frames = train.groupby("group").size()
    class_trials = train.groupby("label").group.nunique()
    weights = np.array([(args.priority_weight if label in priority else 1.0) /
                        (trial_frames[group] * class_trials[label])
                        for group, label in zip(train.group, train.label)], dtype=np.float32)
    weights *= len(weights) / weights.sum()
    scaler = StandardScaler().fit(x[masks["train"]], sample_weight=weights)
    mean, scale = scaler.mean_.astype(np.float32), scaler.scale_.astype(np.float32)
    z = ((x - mean) / scale).astype(np.float32)
    model = tf.keras.Sequential([
        tf.keras.layers.Input(shape=(5,)),
        tf.keras.layers.Dense(128, activation="relu"), tf.keras.layers.Dropout(0.3),
        tf.keras.layers.Dense(64, activation="relu"), tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(len(labels), activation="softmax"),
    ])
    model.compile(optimizer="adam", loss="sparse_categorical_crossentropy")
    best_loss, best_weights, stale, history = float("inf"), None, 0, []
    train_indices = np.flatnonzero(masks["train"])
    validation_indices = np.flatnonzero(masks["validation"])
    for epoch in range(args.epochs):
        order = rng.permutation(len(train_indices))
        model.reset_metrics()
        for offset in range(0, len(order), 32):
            batch = order[offset:offset + 32]
            model.train_on_batch(z[train_indices[batch]], y[train_indices[batch]], sample_weight=weights[batch])
        probability = model(z[validation_indices], training=False).numpy()
        val_loss = float(np.mean(-np.log(np.clip(probability[np.arange(len(probability)), y[validation_indices]], 1e-7, 1))))
        history.append({"epoch": epoch + 1, "validation_loss": val_loss})
        if val_loss < best_loss - 1e-5:
            best_loss, best_weights, stale = val_loss, model.get_weights(), 0
        else:
            stale += 1
        if epoch == 0 or (epoch + 1) % 10 == 0:
            print(f"Epoch {epoch+1}: validation_loss={val_loss:.4f}", flush=True)
        if stale >= 8:
            break
    model.set_weights(best_weights)
    print(f"Training finished after {len(history)} epochs; saving candidate.", flush=True)
    args.output_directory.mkdir(parents=True)
    model.save(args.output_directory / "model.keras")
    print("Keras candidate saved; converting TFLite.", flush=True)
    model_bytes = convert_to_tflite(model, temporary_parent=args.output_directory)
    (args.output_directory / "model.tflite").write_bytes(model_bytes)
    print("TFLite converted; evaluating and verifying export parity.", flush=True)
    interpreter = tf.lite.Interpreter(model_content=model_bytes, num_threads=1)
    interpreter.allocate_tensors()
    input_info, output_info = interpreter.get_input_details()[0], interpreter.get_output_details()[0]
    if input_info["shape"].tolist() != [1, 5] or output_info["shape"].tolist() != [1, len(labels)]:
        raise ValueError("Unexpected TFLite input/output shape")
    if input_info["dtype"] != np.float32 or output_info["dtype"] != np.float32:
        raise ValueError("This deployment requires float32 TFLite tensors")
    tflite_probabilities = []
    for sample in z:
        interpreter.set_tensor(input_info["index"], sample[None, :])
        interpreter.invoke()
        tflite_probabilities.append(interpreter.get_tensor(output_info["index"])[0])
    probabilities = np.array(tflite_probabilities)
    keras_probabilities = model(z, training=False).numpy()
    error = float(np.max(np.abs(probabilities - keras_probabilities)))
    if error > 1e-4:
        raise ValueError(f"Keras/TFLite parity failed: {error}")
    predictions = probabilities.argmax(axis=1)
    evaluations = {}
    for split, mask in masks.items():
        indices = np.flatnonzero(mask)
        subset = data.loc[mask]
        trial_results = []
        for group in sorted(subset.group.unique()):
            trial_mask = data.group.eq(group).to_numpy()
            predicted = int(probabilities[trial_mask].mean(axis=0).argmax())
            true = int(y[np.flatnonzero(trial_mask)[0]])
            trial_results.append({"group": group, "true": labels[true], "predicted": labels[predicted], "correct": predicted == true})
        covered = sorted(set(y[indices].tolist()))
        evaluations[split] = {
            "frames": len(indices), "trials": len(trial_results),
            "covered_labels": [labels[index] for index in covered],
            "frame_top1": float(accuracy_score(y[indices], predictions[indices])),
            "frame_macro_f1": float(f1_score(y[indices], predictions[indices], labels=covered, average="macro", zero_division=0)),
            "frame_confusion_matrix": confusion_matrix(y[indices], predictions[indices], labels=list(range(len(labels)))).tolist(),
            "trial_mean_probability_top1": float(np.mean([trial["correct"] for trial in trial_results])),
            "trial_results": trial_results,
        }
    metadata = {
        "schema_version": "static-recorded-mlp-v1", "data_origin": "real", "classes": labels,
        "tensorflow_version": tf.__version__, "keras_version": tf.keras.__version__,
        "feature_cols": FEATURES, "mean": mean.tolist(), "scale": scale.tolist(), "calibration": config,
        "sources": sources, "excluded_frames": excluded, "trials_per_class": counts, "seed": args.seed,
        "priority_labels": sorted(priority), "priority_weight": args.priority_weight,
        "split_strategy": "whole session/trial groups; seed-shuffled per class; one validation and one test trial when >=3 trials, otherwise train-only",
        "evaluation_scope": "trial-held-out within collected sessions; not independently verified signer or session generalization",
        "architecture": "5 -> Dense(128,relu) -> Dropout(.3) -> Dense(64,relu) -> Dropout(.2) -> Dense(classes,softmax)",
        "training_weighting": "equal total weight per training trial within class; class totals multiplied by explicit priority weight",
        "epochs_run": len(history), "best_validation_loss": best_loss,
        "tflite_size_bytes": len(model_bytes), "tflite_sha256": hashlib.sha256(model_bytes).hexdigest(),
        "keras_tflite_max_probability_error": error,
        "evaluations": evaluations, "hardware_inference_latency_ms": None, "hardware_validation": "Not run",
        "final_accuracy_claim_ready": False,
        "limitations": ["Small team dataset", "Correlated frames within trials", "No rest/unknown class; model always selects a supported class", "Calibrated channels clamp at the measured bent/straight endpoints recorded in calibration metadata", "Recorded signer IDs are metadata, not verified independent people"],
    }
    save_json(args.output_directory / "metadata.json", metadata)
    save_json(args.output_directory / "split_manifest.json", {"assignments": assignments, "sources": sources})
    save_json(args.output_directory / "history.json", history)
    if args.export_header:
        write_header(args.export_header, model_bytes, labels, mean, scale, config)
    faulthandler.cancel_dump_traceback_later()
    print(json.dumps({"classes": labels, "trials_per_class": counts, "epochs": len(history),
                      "tflite_size_bytes": len(model_bytes), "parity_error": error,
                      "evaluation": {name: {key: value for key, value in result.items()
                                             if key not in {"frame_confusion_matrix", "trial_results"}}
                                     for name, result in evaluations.items()}}, indent=2), flush=True)


if __name__ == "__main__":
    main()
