// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjjIj4VI2ydynl1-oiiXza3st_5UjzjXg',
    appId: '1:601431395453:web:9addbba5732c050fc87514',
    messagingSenderId: '601431395453',
    projectId: 'helping-hand-43f25',
    authDomain: 'helping-hand-43f25.firebaseapp.com',
    storageBucket: 'helping-hand-43f25.firebasestorage.app',
    measurementId: 'G-QK950XH99E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK3dirYIAxGkEO0BhTWBh05NB-Bj8zCiI',
    appId: '1:601431395453:android:356358c589b4af77c87514',
    messagingSenderId: '601431395453',
    projectId: 'helping-hand-43f25',
    storageBucket: 'helping-hand-43f25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX6hIl6LhRNpiR29Ye_cjNoEqeVHDjM_Q',
    appId: '1:601431395453:ios:c0dc13d639365089c87514',
    messagingSenderId: '601431395453',
    projectId: 'helping-hand-43f25',
    storageBucket: 'helping-hand-43f25.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX6hIl6LhRNpiR29Ye_cjNoEqeVHDjM_Q',
    appId: '1:601431395453:ios:c0dc13d639365089c87514',
    messagingSenderId: '601431395453',
    projectId: 'helping-hand-43f25',
    storageBucket: 'helping-hand-43f25.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjjIj4VI2ydynl1-oiiXza3st_5UjzjXg',
    appId: '1:601431395453:web:81df2de5772b54d7c87514',
    messagingSenderId: '601431395453',
    projectId: 'helping-hand-43f25',
    authDomain: 'helping-hand-43f25.firebaseapp.com',
    storageBucket: 'helping-hand-43f25.firebasestorage.app',
    measurementId: 'G-0W8N9RLNSG',
  );
}
